# Welcome to Jekyll!

# Website settings
title: Mancoxu
description: Manco's blog,use Jekyll and github pages.
keywords: Manco,my-site,blog,Jekyll,github,gh-pages
baseurl:   # if you have suburl as homepage like '/homepage', please change it to '/homepage'
url: http://mancoxu.github.io/my-site  # url should be changed to 'http://www.jack003.com/homepage' as before
# url: http://127.0.0.1:4000
img_path: /my-site/static/assets/img/blog  # url should be changed to '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: GitHub  # Be used at blog posts' author.
  first_name: 老  # Be used at index page about me section.
  last_name: 可  # Be used at index page about me section.
  cv: http://mancoxu.me  # A online CV can be printed as PDF, leave blank if you don't have now
  email: mancoxu@foxmail.com  # Leave blank if you don't have now
  #facebook_username: jiakunnj  # Leave blank if you don't have now
  github_username: mancoxu  # Leave blank if you don't have now
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: 代码虐我, 我虐键盘. 此循环由来已久 .

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: mancoxu
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not


# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
